apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: demo-nginx
  labels:
    app: demo-nginx
spec:
  clusterLabels:
    matchLabels:
      region: EU
      environment: Dev
  clusterReplicas: 1
  resourceHint: {}
  resourceSelector: {}
