apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: pp-demoliberty
  labels:
    app: demoliberty
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      region: EU
  resourceHint:
    type: cpu
