apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: ar-demoliberty
  labels:
    app: demoliberty
spec:
  type: contains
  source:
    kind: Application
    name: demoliberty
  destination:
    kind: Deployable
    name: dp-demoliberty
