apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demoliberty
  labels:
    app: demoliberty
spec:
  selector:
    matchLabels:
      app: demoliberty
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
