apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: demoliberty
  labels:
    app: demoliberty
spec:
  deployer:
    kind: helm
    helm:
      repository: argocd
      chartName: demoliberty
      version: 1.3.0
      namespace: default
