apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: demoliberty
  labels:
    app: demoliberty
spec:
  deployer:
    kind: helm
    helm:
      repository: ibm-charts
      chartName: ibm-open-liberty
      version: 1.7.0
      namespace: default
