apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: demoliberty
  labels:
    app: demoliberty
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://github.com/niklaushirt/gitops-playground/blob/master/charts/demoliberty-1.3.0.tgz
      namespace: default
