apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: dp-demoliberty
  labels:
    app: demoliberty
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://github.com/niklaushirt/charts/blob/master/helm/charts/repo/stable/demoliberty-1.3.0.tgz
      namespace: default
