apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: demoliberty
  labels:
    app: demoliberty
spec:
  clusterLabels:
    matchLabels:
      name: iks-eu-west
  clusterReplicas: 1
  resourceHint: {}
  resourceSelector: {}
